[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_program = "3KwcL4cGq1yuM8s4Wt5ZfpsH53SfSPtu874CLq8PtU8S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/amandeepsingh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
