[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_token = "78D2NexR2uwVAauba88UrPs7cWKnJtvGyjKsUbqpdXsJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/amandeepsingh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
